### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by daoudeddy** [ricardojlrufino/anyka_v380ipcam_experiments#2]
Hello, I have a an AK3918E V330, when I try to install a patched update the system boots normally disregarding the patch, while the original patch works fine, even tho I modified the patchv380 to make the header look the same like the original patch and still not working for me, and after some investigations it looks like there's a footer at the end of the patch that patchv380 doesn't include in the process

Have you ever encounter this problem? And if so do you have any idea how to create or install custom patches

 Thank you

Here's the original patch file
[正式升级包_V380_安凯_3918E-V330__V1.1.4.0_2022-01-05.zip](https://github.com/ricardojlrufino/anyka_v380ipcam_experiments/files/8247172/_V380_._3918E-V330__V1.1.4.0_2022-01-05.zip)

**Comment by ricardojlrufino** [comment]
Check this:
https://blog.caller.xyz/v380-ipcam-firmware-patching/

**Comment by daoudeddy** [comment]
In the updater sequence part… is there anyway to know which one is failing?

**Comment by ricardojlrufino** [comment]
please, ask author:
https://github.com/bcaller/v380-ipcam-firmware-patch

**Comment by daoudeddy** [comment]
Okay, thanks for your help
