### ISSUE TITLE
Getting audio playback work

### ISSUE THREAD

**Issue by pcmester** [ricardojlrufino/anyka_v380ipcam_experiments#5]
Hi!
When I tried to run aplay, I got this error:

```
open /dev/akpcm_cdev0 failed: Operation not permitted

[ak_cmd_register_module:741] no server was register, can not register module

[ao_sysipc_bind_handle:477] ao handle is not working

[open:297] init aec ao failed
```
Do you know a fix for this?

**Comment by ricardojlrufino** [comment]
You are using this ?
https://github.com/ricardojlrufino/anyka_v380ipcam_experiments/tree/master/apps/ak_aplay

**Comment by pcmester** [comment]
Yes, I am

**Comment by ricardojlrufino** [comment]
You need stop any services using : /dev/akpcm_cdev0
or you need start audio driver...

**Comment by pcmester** [comment]
Thank you, I will try that
